### ISSUE TITLE
!config not working

### ISSUE THREAD

**Issue by derGraph** [e4c6/DiscordGPT-3#1]
If I type !confi, !allowance, !length; the bot doesn't respond
![image](https://user-images.githubusercontent.com/68235499/105961296-9f518e00-607e-11eb-8988-3e576b60f592.png)

**Comment by e4c6** [comment]
Hi, i assume you've caught the bot while it was offline. Can you try again?

**Comment by derGraph** [comment]
No, not working now.

Am Do., 28. Jan. 2021 um 16:53 Uhr schrieb e4c6 <notifications@github.com>:

**Comment by derGraph** [comment]
I think it doesn't detect me as an Owner, but I am the only one.


Am Do., 28. Jan. 2021 um 17:55 Uhr schrieb Paul Graf <
paulantongraf@gmail.com>:

**Comment by e4c6** [comment]
@PaulderGraph Can you please try kicking the bot and adding it back in? It's likely that you've added the bot while it was offline so it wasn't able to record you as the owner. If that doesn't work out, please contact me on discord so i can look into the database for your server.

**Comment by e4c6** [comment]
Fixed in [5d022f85b2e38a1d552a9458dda136a0192fbf9f](https://github.com/e4c6/DiscordGPT-3/commit/5d022f85b2e38a1d552a9458dda136a0192fbf9f).
