### ISSUE TITLE
Could need some support with manual setup on RPI4

### ISSUE THREAD

**Issue by ClaraCrazy** [e4c6/DiscordGPT-3#13]
Hey. So as noted in the previous issue, there is no compatible docker mongo for the RPI4 running raspbian

I would like to run this on my raspyberry tho. The old way of me doing it was messed up so lets not talk about that.

I have my mongo database on the "cloud.mongodb.com" website. how would I go on from there? I have set up a user but what confuses me is the host & port. (thats where my old solution was just messed up)

Quick chat on discord perhaps?

**Comment by e4c6** [comment]
Can you try using the image from https://registry.hub.docker.com/r/webhippie/mongodb?

`docker pull webhippie/mongodb:latest` and change the image name at docker-compose file.

**Comment by ClaraCrazy** [comment]
that seems to work however im now stuck at this:

`Step 3/7 : RUN apk add --no-cache gcc musl-dev linux-headers
 ---> Running in 099339d17101
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
3069399952:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069399952:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069399952:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069399952:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069399952:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: Permission denied
ERROR: unable to select packages:
  gcc (no such package):
    required by: world[gcc]
  linux-headers (no such package):
    required by: world[linux-headers]
  musl-dev (no such package):
    required by: world[musl-dev]
The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3
ERROR: Service 'bot' failed to build : Build failed`

**Comment by ClaraCrazy** [comment]
The urls work on my pc and I can even download the files there.
just running "curl  https://dl-cdn.alpinelinux.org/alpine/v3.13/community" works fine. so is there a way to download that stuff manually and skip that step?
