### ISSUE TITLE
Problem with env

### ISSUE THREAD

**Issue by altair2022** [e4c6/DiscordGPT-3#18]
Hi, I encountered a problem with environment varibles.

`container.config.DISCORD_TOKEN.from_env("DISCORD_TOKEN", required=True)
  File "src/dependency_injector/providers.pyx", line 1703, in dependency_injector.providers.ConfigurationOption.from_env
ValueError: Environment variable "DISCORD_TOKEN" is undefined`

Already set the .env with the required value, also updated the following dependencies.

**Comment by youthyio** [comment]
How did you fix this?
